[Service]
BindPaths=/opt/microsoft/intune/etc/os-release:/etc/os-release
BindPaths=/opt/microsoft/intune/etc/os-release:/usr/lib/os-release
Environment=LD_PRELOAD=/opt/microsoft/intune/lib/libcrypto.so.3.2.6:/opt/microsoft/intune/lib/libssl.so.3.2.6
